modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory 
issueTrackerURL="https://github.com/TelepathicGrunt/Bumblezone/issues" #optional
license="https://github.com/TelepathicGrunt/Bumblezone/blob/latest-released/LICENSE"

[[mods]] #mandatory
modId="the_bumblezone" #mandatory
logoFile= "../assets/the_bumblezone/the_bumblezone_logo_large.png"
logoBlur=false
version="${version}" #mandatory
displayName="The Bumblezone" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge"
authors="TelepathicGrunt"
credits="Thanks to Commoble for suggesting this awesome name for this mod! Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
description='''A wonderful bee dimension mod with lots of new exploration and adventuring to do! Check out the advancements for how to play the mod!
'''

[[dependencies.the_bumblezone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"

[[dependencies.the_bumblezone]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.1,)"
