modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TelepathicGrunt/Bumblezone/issues"
license="https://github.com/TelepathicGrunt/Bumblezone/blob/latest-released/LICENSE"

[[mods]]
    modId="the_bumblezone"
    logoFile= "assets/the_bumblezone/the_bumblezone_logo_large.png"
    logoBlur=false
    version="${version}"
    displayName="The Bumblezone"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge"
    authors="TelepathicGrunt"
    credits="Thanks to Commoble for suggesting this awesome name for this mod! Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
    description='''A wonderful bee dimension mod with lots of new exploration and adventuring to do! Check out the advancements for how to play the mod!
    '''

[[mixins]]
    config = "the_bumblezone-neoforge.mixins.json"

[[mixins]]
    config = "the_bumblezone-common.mixins.json"

[[dependencies.the_bumblezone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"

[[dependencies.the_bumblezone]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.40-beta,)"

[[dependencies.the_bumblezone]]
    modId="productivebees"
    type="optional"
    ordering="AFTER"
    versionRange="[0,)"

[[dependencies.the_bumblezone]]
    modId="resourcefulbees"
    type="optional"
    ordering="AFTER"
    versionRange="[0,)"